[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production.variables]
NODE_ENV = "production"
PORT = "$PORT"
DATABASE_URL = "$DATABASE_URL"
JWT_SECRET = "$JWT_SECRET"
JWT_REFRESH_SECRET = "$JWT_REFRESH_SECRET"
BLOB_READ_WRITE_TOKEN = "$BLOB_READ_WRITE_TOKEN"
REDIS_URL = "$REDIS_URL"
SENTRY_DSN = "$SENTRY_DSN"
APP_URL = "$APP_URL"
BCRYPT_SALT_ROUNDS = "12"
JWT_EXPIRES_IN = "7d"
JWT_REFRESH_EXPIRES_IN = "30d"
API_VERSION = "v1"
APP_NAME = "DoramaFlix"