# =============================================
# DORAMAFLIX - PROMETHEUS ALERTS
# Critical alerts for production monitoring
# =============================================

groups:
  # =============================================
  # APPLICATION ALERTS
  # =============================================
  
  - name: doramaflix-application
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for {{ $labels.job }}."

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.job }}."

      - alert: BackendHealthCheckFailed
        expr: up{job="doramaflix-backend"} == 0
        for: 30s
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Backend health check failed"
          description: "DoramaFlix backend is not responding to health checks."

      - alert: FrontendHealthCheckFailed
        expr: up{job="doramaflix-frontend"} == 0
        for: 30s
        labels:
          severity: critical
          team: frontend
        annotations:
          summary: "Frontend health check failed"
          description: "DoramaFlix frontend is not responding to health checks."

  # =============================================
  # DATABASE ALERTS
  # =============================================
  
  - name: doramaflix-database
    rules:
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding."

      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "High database connection usage"
          description: "PostgreSQL connection usage is {{ $value }}%."

      - alert: DatabaseLockWaits
        expr: rate(pg_stat_database_blks_read[5m]) > 1000
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "High database lock waits"
          description: "PostgreSQL is experiencing high lock waits."

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          team: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache server is not responding."

      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          team: cache
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value }}%."

  # =============================================
  # INFRASTRUCTURE ALERTS
  # =============================================
  
  - name: doramaflix-infrastructure
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}."

      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }}."

      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000  # 100MB/s
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High network traffic"
          description: "High network traffic detected on {{ $labels.instance }}."

  # =============================================
  # BUSINESS METRICS ALERTS
  # =============================================
  
  - name: doramaflix-business
    rules:
      - alert: LowUserRegistrations
        expr: rate(user_registrations_total[1h]) < 1
        for: 1h
        labels:
          severity: warning
          team: product
        annotations:
          summary: "Low user registration rate"
          description: "User registration rate is below expected threshold."

      - alert: HighVideoUploadFailures
        expr: rate(video_upload_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High video upload failure rate"
          description: "Video upload failure rate is {{ $value }} per second."

      - alert: PaymentProcessingErrors
        expr: rate(payment_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
          team: payments
        annotations:
          summary: "Payment processing errors detected"
          description: "Payment processing is failing at {{ $value }} errors per second."

  # =============================================
  # EXTERNAL DEPENDENCIES
  # =============================================
  
  - name: doramaflix-external
    rules:
      - alert: ExternalServiceDown
        expr: probe_success == 0
        for: 2m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "External service is down"
          description: "{{ $labels.instance }} is not responding to health checks."

      - alert: SSLCertificateExpiring
        expr: probe_ssl_earliest_cert_expiry - time() < 7 * 24 * 3600  # 7 days
        for: 1h
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value | humanizeDuration }}."

      - alert: HighLatencyToExternalService
        expr: probe_duration_seconds > 5
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High latency to external service"
          description: "Latency to {{ $labels.instance }} is {{ $value }}s."